### ISSUE TITLE
[bug] Back To Top Button Overlapping with Cancel Button

### ISSUE THREAD

**Issue by Rishav1707** [WeMakeDevs/wemakedevs#447]
### Describe the bug

![colliding](https://user-images.githubusercontent.com/97666287/219868049-5e9696a8-be8b-4770-bf07-6799af3e7d7c.png)

### To Reproduce

1. Go to https://wemakedevs.org/
2. `Right` click and `inspect` the website.
3. Set the screen size to `375px`.
4. See the error at botton right corner.

### Expected Behavior

![colliding fixed](https://user-images.githubusercontent.com/97666287/219868157-833cd627-31da-49e0-8c2f-9157e934aab9.png)

**Comment by Rishav1707** [comment]
Shall I work on this issue?

**Comment by Sreejit-Sengupto** [comment]
@Chandraprakash-Darji please assign him! He's caught a bug.

**Comment by Divyanshu1020** [comment]
This is very easy we have just to remove bottom: 30px;

```css
@media only screen and (max-width: 480px)
.ScrollToTop_btn--image__7dFi\+ {
    /* bottom: 30px; */
    font-size: 3em;
    position: fixed;
    right: 10px;
}
```
![Screenshot (23)](https://user-images.githubusercontent.com/97149795/219900774-95e2c494-dd6d-449c-9ff7-22ac1e411ed8.png)


Can I create my first pull request?
