### ISSUE TITLE
[feat] The footer socials icon hover experience can be enhanced

### ISSUE THREAD

**Issue by SaptarshiSarkar12** [WeMakeDevs/wemakedevs#716]
### Would you like to have a new feature? Please describe.

The footer of the [WeMakeDevs website](https://wemakedevs.org/) has many social icons, but, when I hover the mouse pointer, the icons still remain as it is without any effects in them. So, I think the hover experience can be made better.
### Effects that can be added to the icons :
- On hovering, the icons can have colour specific to the social branding colour
- On hovering, the icons can have **ease-in-out** _transition_ with a **delay of around 200-300 seconds**

### How would this feature be beneficial for the project

It might have a good and cool impression on the end user. So, it effectively makes the Website footer visually more appealing.

### Additional context

I have provided below a video describing the effects I have mentioned.

https://github.com/WeMakeDevs/wemakedevs/assets/105960032/af32b05f-a705-439d-b93e-4e4661ddefca

**Comment by SaptarshiSarkar12** [comment]
If the issue looks good to the maintainers, can I work on this?

**Comment by Shiva953** [comment]
I would like to take this up!

**Comment by AnuragThePathak** [comment]
Thoughts @Chandraprakash-Darji thoughts?

**Comment by Chandraprakash-Darji** [comment]
@AnuragThePathak Looks cool

**Comment by SaptarshiSarkar12** [comment]
Can I work on it @Chandraprakash-Darji @AnuragThePathak ?

**Comment by siddhant-khisty** [comment]
@SaptarshiSarkar12 feel free to work on this

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 feel free to work on this

Thank you @siddhant-khisty for assigning me :grinning: !

**Comment by SaptarshiSarkar12** [comment]
@siddhant-khisty I am able to set the icon colour but I am unable to set the hover effect of the icons. Can you please help me out?

**Comment by riyaz1523** [comment]
@SaptarshiSarkar12 Can you share the css code that you have added? I'll help you

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 Can you share the css code that you have added? I'll help you

Yes, I have added 
```css
.FaYoutube:hover {
  color: #FF0000;
}
```
in [`index.module.css` file](https://github.com/WeMakeDevs/wemakedevs/blob/main/src/components/layout/Footer/index.module.css).

@riyaz1523 Do you want the whole css file?

**Comment by riyaz1523** [comment]
@SaptarshiSarkar12  I think you have added the respective colors to the icons. Using colored instead will give a rich look also for hovering we can use the example
The below code contains the .icons as the specific icon container. Use the below code and let me know
`.icons{
  transition: transform 0.4s ease;
}
.icons:hover{
  transform: translateY(-2px);
}`

**Comment by SaptarshiSarkar12** [comment]
> @SaptarshiSarkar12 I think you have added the respective colors to the icons. Using colored instead will give a rich look also for hovering we can use the example The below code contains the .icons as the specific icon container. Use the below code and let me know `.icons{ transition: transform 0.4s ease; } .icons:hover{ transform: translateY(-2px); }`

@riyaz1523 I have tried that but still it does not work. I don't know why.

**Comment by Shiva953** [comment]
maybe try adding tailwind classes as : 
`className={`text-2xl transition-all duration-200 ease-in-out delay-200 hover:text-${link.color} hover:-translate-y-1`}`
in [this](https://github.com/WeMakeDevs/wemakedevs/blob/e3985947b5d37a21f3671ecc49cf6fafb1a2b176/src/components/layout/Footer.jsx#L78C11-L89C17) part of the Footer.jsx file


and then add the` color` property inside each object of the `links` array

**Comment by riyaz1523** [comment]
Okay. Share the whole css code for the footer section that you have written to riyazramzan2001@gmail.com. Will look into it

**Comment by SaptarshiSarkar12** [comment]
> Okay. Share the whole css code for the footer section that you have written to [riyazramzan2001@gmail.com](mailto:riyazramzan2001@gmail.com). Will look into it

@riyaz1523 Can I share it here?

**Comment by riyaz1523** [comment]
@SaptarshiSarkar12 okay

**Comment by SaptarshiSarkar12** [comment]
@riyaz1523 here is the css code :arrow_down: 
```css
.footer {
  background-color: var(--clr-base-200);
  color: var(--clr-content);
  padding-block: 6rem;
}

.layout {
  display: flex;
  flex-direction: column;
  gap: 1rem;
}

.details {
  display: flex;
  justify-content: space-between;
}

.details h3 {
  font-size: 2rem;
  font-weight: 700;
  text-transform: uppercase;
  text-align: right;
}

.join {
  display: flex;
  flex-direction: column;
  gap: 1rem;
  align-items: flex-start;
}

.join h3 {
  font-size: 1.5rem;
  text-align: left;
}

.join a {
  color: var(--clr-content);
  font-size: 1.5rem;
  display: flex;
  align-items: center;
  gap: 1rem;
  justify-content: center;
}

.socialSection {
  font-size: 2rem;
  display: flex;
  justify-content: space-between;
  border-top: 1px solid var(--clr-content);
  border-bottom: 1px solid var(--clr-content);
  padding-block: 1rem;
  margin-top: 5rem;
}

.socialSection a {
  font-size: 1.5rem;
  margin-inline: 0.25rem;
}

.links {
  display: flex;
  gap: 1rem;
  align-items: center;
  flex-wrap: wrap;
}

.links a:hover {
  color: var(--clr-primary);
  transition: color 0.3s ease-in;
}

.copyright {
  font-size: 1.2rem;
  text-align: center;
  margin-block-start: 2rem;
}

.linkGroups {
  display: grid;
  grid-template-columns: repeat(4, min-content);
  padding: 1rem;
  width: 100%;
  margin: auto;
  justify-content: space-between;
}

.linkGroups ul {
  list-style: none;
}

.linksHeading {
  width: fit-content;
  border-bottom: 1px solid var(--clr-primary);
  padding-bottom: 0.75rem;
  margin-bottom: 1rem;
  font-size: 1.15rem;
}

.linkGroups li {
  margin: 1rem 0;
  font-size: 0.95rem;
  font-weight: 400;
}

.linkGroups li a {
  padding-bottom: 3px;
}

@media (max-width: 900px) {
  .footer {
    padding-block: 2rem;
    text-align: center;
    padding-block-end: 6rem;
  }

  .details {
    flex-direction: column;
    gap: 1rem;
  }

  .join {
    align-items: center;
    margin-bottom: 0.3rem;
  }

  .details h3 {
    text-align: center;
  }

  .details h3 {
    font-size: 1.3rem;
  }

  .socialSection {
    flex-direction: column;
    gap: 1rem;
    align-items: center;
    margin-top: 1rem;
  }

  .links {
    width: 100%;
    justify-content: center;
  }

  .copyright {
    margin-top: 1rem;
  }

  .linkGroups {
    grid-template-columns: repeat(2, min-content);
    text-align: left;
    row-gap: 2rem;
    width: 70%;
  }

  .linksHeading {
    font-size: 1rem;
  }

  .linkGroups li {
    font-size: 0.9rem;
  }
}

@media (max-width: 600px) {
  .linkGroups {
    width: 80%;
  }

  .linksHeading {
    font-size: 0.95rem;
  }

  .linkGroups li {
    font-size: 0.8rem;
  }
}

@media (max-width: 450px) {
  .linkGroups {
    width: 90%;
    grid-template-columns: repeat(2, 1fr);
    padding: 0;
  }

  .linksHeading {
    font-size: 0.9rem;
  }

  .linkGroups li {
    font-size: 0.7rem;
  }
}

.icons { transition: transform 0.4s ease; } 
.icons:hover { transform: translateY(-2px); }
```
